# Generated by Django 4.2.6 on 2023-10-23 20:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0002_product_image_product_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='created',
            new_name='actualizado',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='updated',
            new_name='creado',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='image',
            new_name='imagen',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='price',
            new_name='precio',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='title',
            new_name='titulo',
        ),
    ]
