# Generated by Django 4.2.6 on 2023-10-23 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0004_product_mililitros'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='mililitros',
            field=models.IntegerField(null=True),
        ),
    ]
