# Generated by Django 4.2.6 on 2023-10-24 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0006_product_categoria_alter_product_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='categoria',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
